apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
  namespace: elastic-system
data:
  logstash.conf: |
    input {
      beats {
        port => 5044
      }
    }
    filter {
      grok {
        match => { "message" => "%{COMBINEDAPACHELOG}" }
      }
    }
    output {
      elasticsearch {
        hosts => ["https://quickstart-es-http.elastic:9200"]
        user => "elastic"
        password => "co2Ddc92Zr95B5CLjU690dd2"
        ssl => true
        cacert => '/usr/share/logstash/config/certs/ca.crt'
      }
      stdout { codec => rubydebug }
    }
