apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::296062593948:role/cert-manager
  name: cert-manager
  namespace: cert-manager
